In [11]:
import numpy as np

### 1. Create a 4x4 matrix with values ranging from 0 to 3.
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [22]:
arr=np.zeros((4,4))
arr[1]=1
arr[2]=2
arr[3]=3
arr.T

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

### 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis![](image/assignment.png)

In [27]:
ar = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11],
                [12, 13, 14, 15]])
ar1 = np.hsplit(ar,2)
ar1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

####  3. soal tambahan:

misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

In [88]:
import math

def is_prime(n):
    if n % 2 == 0 and n > 2 : 
        return False
    return all(n % i for i in range(3, int(math.sqrt(n)) + 1, 2))

a= np.array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], 
             [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
a=a.reshape(1,25)
a=a.ravel()
index=[0]
an=np.delete(a,index)
foo = np.vectorize(is_prime)
pbools = foo(an)
primes = np.extract(pbools, an)
primes
    

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])