In [1]:
import numpy as np

In [5]:
arr=np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
a[1:4,1:3]
#a[baris,kolom]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [24]:
b=np.zeros(10)
b[4]=11
b

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

In [29]:
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
c.reshape((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

no.3 pakai function