# Library Numpy

### 1. Import library Numpy

In [8]:
import numpy as np

### 2. Look at the version 

In [1]:
np.__version__

NameError: name 'np' is not defined

### 3. Getting Help

In [3]:
np.info(np.array)

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major).
    If object 

## What is Array?

### 4. List vs Numpy

In [4]:
# Python List
list1 = [1, 2, 3, 4, 5]
list2 = [i*2 for i in range(1, 6)] # 1 2 3 4 5 

print('list1:', list1)
print('list2:', list2)

list1: [1, 2, 3, 4, 5]
list2: [2, 4, 6, 8, 10]


In [3]:
print('type of data list1 :', type(list1))

type of data list1 : <class 'list'>


In [4]:
 list1 + list2

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

In [5]:
list3 = []
for a, b in zip(list1, list2):
    list3.append(a+b)
list3

[3, 6, 9, 12, 15]

In [5]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
list3 = []
for a, b in zip(list1, list2):
    list3.append(a*b)
list3

[2, 8, 18, 32, 50]

In [9]:
#numpy
np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([i*2 for i in range(1, 6)])

print(np1)
print(np2)

[1 2 3 4 5]
[ 2  4  6  8 10]


## Exercise 2 

In [12]:
from numpy import random

#### 1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [13]:
random.randint(0, 101, size=(5,))

array([65, 58, 90, 84, 14])

#### 2.Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [14]:
random.randint(0, 101, size=(3,5,))

array([[72, 11, 76, 81, 51],
       [96, 45, 16, 57, 30],
       [ 4, 93,  6, 81, 88]])

#### 3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [21]:
np.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])